name: PR Label Commands

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  handle-pr-label-commands:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout utilities
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/utilities

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install PyGithub

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_KEY }}

      - name: Run label-from-comment script
        run: python .github/utilities/add_label_from_comment.py
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
